import {
  Project,
  Task,
  Lead,
  DailyCallLog,
  PipelineDeal,
  ConnectedSystem,
} from "./types";

// ─── Projects ─────────────────────────────────────────────
export const mockProjects: Project[] = [
  {
    id: "proj-1",
    name: "Media Buying Campaigns",
    description: "Google & Meta ad campaigns for clients. Managing budgets, creatives, and optimization across all active accounts.",
    category: "Marketing",
    status: "Active",
    progress: 65,
    lastUpdated: "2026-02-18",
    notes: "Q1 budgets approved. Need to launch 3 new campaigns this week. CPA trending down on Meta — keep scaling.",
    color: "bg-blue-500",
  },
  {
    id: "proj-2",
    name: "Supabase Audit & Migration",
    description: "Audit existing Supabase setup, optimize RLS policies, migrate legacy data, and set up proper backups.",
    category: "Infrastructure",
    status: "Active",
    progress: 40,
    lastUpdated: "2026-02-17",
    notes: "RLS audit complete. Found 3 tables without policies. Migration script 60% done.",
    color: "bg-emerald-500",
  },
  {
    id: "proj-3",
    name: "VAPI Agent Setup",
    description: "Building AI voice agents for inbound and outbound calls. Integrating with CRM and calendar.",
    category: "Development",
    status: "Active",
    progress: 30,
    lastUpdated: "2026-02-16",
    notes: "Inbound agent working. Outbound needs Twilio integration. Test with 10 calls before scaling.",
    color: "bg-violet-500",
  },
  {
    id: "proj-4",
    name: "n8n Workflow Automation",
    description: "Building automation workflows: lead enrichment, email sequences, Slack notifications, reporting pipelines.",
    category: "Operations",
    status: "Active",
    progress: 55,
    lastUpdated: "2026-02-18",
    notes: "Lead enrichment flow live. Email sequence flow in testing. Need to build Stripe → Slack notification flow.",
    color: "bg-orange-500",
  },
  {
    id: "proj-5",
    name: "Cold Calling Operation",
    description: "Daily cold call campaigns targeting home service businesses. 240 dials/day target.",
    category: "Sales",
    status: "Active",
    progress: 78,
    lastUpdated: "2026-02-18",
    notes: "Hitting dial targets consistently. Demo booking rate improving. Need to add 50 new FL leads this week.",
    color: "bg-red-500",
  },
  {
    id: "proj-6",
    name: "Client Onboarding System",
    description: "Streamlined onboarding flow: contracts, intake forms, project setup, kickoff calls, and first-week checklist.",
    category: "Client Work",
    status: "Active",
    progress: 85,
    lastUpdated: "2026-02-15",
    notes: "Onboarding doc v2 finalized. Automated welcome email working. Need to build intake form in Typeform.",
    color: "bg-teal-500",
  },
  {
    id: "proj-7",
    name: "Content Strategy & Calendar",
    description: "Planning and executing content across YouTube, Twitter/X, LinkedIn. Weekly posting schedule.",
    category: "Strategy",
    status: "On Hold",
    progress: 20,
    lastUpdated: "2026-02-10",
    notes: "Paused to focus on cold calling push. Resume March. Have 5 video ideas drafted.",
    color: "bg-pink-500",
  },
  {
    id: "proj-8",
    name: "HomeField Hub Website Redesign",
    description: "Full redesign of homfieldhub.com — new copy, case studies, booking flow, and SEO optimization.",
    category: "Development",
    status: "Planning",
    progress: 10,
    lastUpdated: "2026-02-12",
    notes: "Wireframes sketched. Need to finalize copy and gather client testimonials. Target launch: March 15.",
    color: "bg-cyan-500",
  },
  {
    id: "proj-9",
    name: "Stripe Billing Setup",
    description: "Configuring Stripe for recurring client billing, invoicing, and payment tracking.",
    category: "Infrastructure",
    status: "Completed",
    progress: 100,
    lastUpdated: "2026-02-08",
    notes: "All clients on auto-billing. Webhook to Slack working. Monthly reconciliation automated.",
    color: "bg-green-500",
  },
  {
    id: "proj-10",
    name: "CRM & Data Pipeline",
    description: "Building a unified data pipeline from lead sources → CRM → client management using Supabase + n8n.",
    category: "Development",
    status: "Planning",
    progress: 15,
    lastUpdated: "2026-02-14",
    notes: "Schema designed. Waiting on Supabase audit to finish before building. ETA: late Feb.",
    color: "bg-amber-500",
  },
];

// ─── Tasks ────────────────────────────────────────────────
export const mockTasks: Task[] = [
  {
    id: "task-1",
    title: "Follow up with Lone Star Concrete — send proposal",
    status: "In progress",
    dueDate: "2026-02-18",
    priority: "High",
    projectId: "proj-5",
    source: "manual",
  },
  {
    id: "task-2",
    title: "Prep demo deck for Precision Plumbing (2/20)",
    status: "Not started",
    dueDate: "2026-02-19",
    priority: "High",
    projectId: "proj-5",
    source: "manual",
  },
  {
    id: "task-3",
    title: "Fix RLS policies on leads table",
    status: "In progress",
    dueDate: "2026-02-19",
    priority: "High",
    projectId: "proj-2",
    source: "manual",
  },
  {
    id: "task-4",
    title: "Research 50 new leads in FL market",
    status: "Not started",
    dueDate: "2026-02-21",
    priority: "Medium",
    projectId: "proj-5",
    source: "manual",
  },
  {
    id: "task-5",
    title: "Build Stripe → Slack notification n8n flow",
    status: "Not started",
    dueDate: "2026-02-20",
    priority: "Medium",
    projectId: "proj-4",
    source: "manual",
  },
  {
    id: "task-6",
    title: "Test VAPI outbound agent with 10 calls",
    status: "Not started",
    dueDate: "2026-02-21",
    priority: "High",
    projectId: "proj-3",
    source: "manual",
  },
  {
    id: "task-7",
    title: "Send onboarding materials to Coastal Concrete Coatings",
    status: "Done",
    dueDate: "2026-02-17",
    priority: "High",
    projectId: "proj-6",
    source: "manual",
  },
  {
    id: "task-8",
    title: "Launch Meta campaign for BlueSky Solar",
    status: "In progress",
    dueDate: "2026-02-19",
    priority: "High",
    projectId: "proj-1",
    source: "manual",
  },
  {
    id: "task-9",
    title: "Invoice BlueSky Solar — February",
    status: "Not started",
    dueDate: "2026-02-28",
    priority: "Medium",
    projectId: null,
    source: "manual",
  },
  {
    id: "task-10",
    title: "Write case study from First Response Restoration results",
    status: "Not started",
    dueDate: "2026-02-25",
    priority: "Low",
    projectId: "proj-7",
    source: "manual",
  },
  {
    id: "task-11",
    title: "Set up Supabase backup cron job",
    status: "Not started",
    dueDate: "2026-02-22",
    priority: "Medium",
    projectId: "proj-2",
    source: "manual",
  },
  {
    id: "task-12",
    title: "Draft wireframes for new website homepage",
    status: "In progress",
    dueDate: "2026-02-24",
    priority: "Medium",
    projectId: "proj-8",
    source: "manual",
  },
];

// ─── Leads ────────────────────────────────────────────────
export const mockLeads: Lead[] = [
  {
    id: "1",
    companyName: "Green Valley Landscaping",
    ownerName: "Mike Johnson",
    phone: "(512) 555-0142",
    state: "TX",
    website: "greenvalleylandscaping.com",
    phoneType: "Mobile",
    status: "New",
    lastCalled: null,
    notes: "",
  },
  {
    id: "2",
    companyName: "Summit Roofing Co",
    ownerName: "Sarah Chen",
    phone: "(404) 555-0198",
    state: "GA",
    website: "summitroofing.com",
    phoneType: "Landline",
    status: "Called",
    lastCalled: "2026-02-17",
    notes: "Left voicemail. Owner busy — call back Thursday.",
  },
  {
    id: "3",
    companyName: "Precision Plumbing",
    ownerName: "Dave Martinez",
    phone: "(813) 555-0276",
    state: "FL",
    website: "precisionplumbingfl.com",
    phoneType: "Mobile",
    status: "Demo Booked",
    lastCalled: "2026-02-16",
    notes: "Demo scheduled for 2/20 at 2pm ET. Very interested.",
  },
  {
    id: "4",
    companyName: "Ace Electric Services",
    ownerName: "Tom Williams",
    phone: "(602) 555-0384",
    state: "AZ",
    website: "aceelectricaz.com",
    phoneType: "VOIP",
    status: "No Answer",
    lastCalled: "2026-02-17",
    notes: "Tried twice. Will try again tomorrow morning.",
  },
  {
    id: "5",
    companyName: "Bright Home Painting",
    ownerName: "Lisa Park",
    phone: "(919) 555-0412",
    state: "NC",
    website: "brighthomepainting.com",
    phoneType: "Mobile",
    status: "Callback",
    lastCalled: "2026-02-15",
    notes: "Call back Monday 2/17 after 3pm.",
  },
  {
    id: "6",
    companyName: "Ironclad Fencing",
    ownerName: "Ryan O'Brien",
    phone: "(214) 555-0533",
    state: "TX",
    website: "ironcladfencing.com",
    phoneType: "Landline",
    status: "Not Interested",
    lastCalled: "2026-02-14",
    notes: "Has existing website provider. Not looking to switch.",
  },
  {
    id: "7",
    companyName: "Clearwater Pool Service",
    ownerName: "Jessica Adams",
    phone: "(407) 555-0647",
    state: "FL",
    website: "clearwaterpools.net",
    phoneType: "Mobile",
    status: "New",
    lastCalled: null,
    notes: "",
  },
  {
    id: "8",
    companyName: "Mountain View HVAC",
    ownerName: "Carlos Rivera",
    phone: "(303) 555-0751",
    state: "CO",
    website: "mountainviewhvac.com",
    phoneType: "VOIP",
    status: "Called",
    lastCalled: "2026-02-17",
    notes: "Spoke briefly. Sending info via email.",
  },
  {
    id: "9",
    companyName: "Liberty Lawn Care",
    ownerName: "James Foster",
    phone: "(615) 555-0823",
    state: "TN",
    website: "libertylawncare.com",
    phoneType: "Mobile",
    status: "New",
    lastCalled: null,
    notes: "",
  },
  {
    id: "10",
    companyName: "Patriot Pest Control",
    ownerName: "Amanda White",
    phone: "(770) 555-0916",
    state: "GA",
    website: "patriotpestcontrol.com",
    phoneType: "Landline",
    status: "Demo Booked",
    lastCalled: "2026-02-16",
    notes: "Demo 2/21 at 10am. Husband & wife run the biz together.",
  },
  {
    id: "11",
    companyName: "Sunshine Gutters",
    ownerName: "Kevin Brown",
    phone: "(480) 555-1024",
    state: "AZ",
    website: "sunshinegutters.com",
    phoneType: "Mobile",
    status: "Callback",
    lastCalled: "2026-02-17",
    notes: "In the field. Call after 5pm.",
  },
  {
    id: "12",
    companyName: "Peak Pressure Washing",
    ownerName: "Nathan Gray",
    phone: "(704) 555-1138",
    state: "NC",
    website: "peakpressurewash.com",
    phoneType: "VOIP",
    status: "New",
    lastCalled: null,
    notes: "",
  },
];

// ─── Call Logs ────────────────────────────────────────────
export const mockCallLogs: DailyCallLog[] = [
  { id: "1", date: "2026-02-18", dials: 187, contacts: 42, conversations: 18, demosBooked: 3 },
  { id: "2", date: "2026-02-17", dials: 243, contacts: 56, conversations: 24, demosBooked: 5 },
  { id: "3", date: "2026-02-14", dials: 221, contacts: 48, conversations: 19, demosBooked: 4 },
  { id: "4", date: "2026-02-13", dials: 256, contacts: 61, conversations: 27, demosBooked: 6 },
  { id: "5", date: "2026-02-12", dials: 198, contacts: 44, conversations: 16, demosBooked: 2 },
  { id: "6", date: "2026-02-11", dials: 234, contacts: 52, conversations: 22, demosBooked: 4 },
  { id: "7", date: "2026-02-10", dials: 210, contacts: 46, conversations: 20, demosBooked: 3 },
];

// ─── Pipeline ─────────────────────────────────────────────
export const mockPipelineDeals: PipelineDeal[] = [
  {
    id: "1",
    companyName: "Green Valley Landscaping",
    ownerName: "Mike Johnson",
    phone: "(512) 555-0142",
    email: "mike@greenvalleylandscaping.com",
    dealValue: 2400,
    stage: "Prospect",
    notes: "Cold lead — just added.",
  },
  {
    id: "2",
    companyName: "Precision Plumbing",
    ownerName: "Dave Martinez",
    phone: "(813) 555-0276",
    email: "dave@precisionplumbingfl.com",
    dealValue: 3600,
    stage: "Demo Scheduled",
    notes: "Demo 2/20 at 2pm ET.",
  },
  {
    id: "3",
    companyName: "Patriot Pest Control",
    ownerName: "Amanda White",
    phone: "(770) 555-0916",
    email: "amanda@patriotpestcontrol.com",
    dealValue: 2400,
    stage: "Demo Scheduled",
    notes: "Demo 2/21 at 10am.",
  },
  {
    id: "4",
    companyName: "Lone Star Concrete",
    ownerName: "Bobby Reed",
    phone: "(210) 555-1247",
    email: "bobby@lonestarconcrete.com",
    dealValue: 4800,
    stage: "Demo Completed",
    notes: "Loved the demo. Waiting on proposal.",
  },
  {
    id: "5",
    companyName: "Evergreen Tree Service",
    ownerName: "Paul Nelson",
    phone: "(503) 555-1359",
    email: "paul@evergreentreeservice.com",
    dealValue: 3600,
    stage: "Proposal Sent",
    notes: "Sent proposal 2/14. Following up Friday.",
  },
  {
    id: "6",
    companyName: "All-Pro Garage Doors",
    ownerName: "Chris Taylor",
    phone: "(972) 555-1461",
    email: "chris@allprogaragedoors.com",
    dealValue: 2400,
    stage: "Proposal Sent",
    notes: "Comparing with competitor.",
  },
  {
    id: "7",
    companyName: "Coastal Concrete Coatings",
    ownerName: "Derek Hall",
    phone: "(843) 555-1572",
    email: "derek@coastalcoatings.com",
    dealValue: 4800,
    stage: "Signed",
    notes: "Signed 2/10. Onboarding this week.",
  },
  {
    id: "8",
    companyName: "First Response Restoration",
    ownerName: "Monica Lee",
    phone: "(678) 555-1683",
    email: "monica@firstresponserestoration.com",
    dealValue: 3600,
    stage: "Active",
    notes: "Client since Jan. Great results so far.",
  },
  {
    id: "9",
    companyName: "BlueSky Solar",
    ownerName: "Angela Morris",
    phone: "(480) 555-1794",
    email: "angela@blueskysolar.com",
    dealValue: 6000,
    stage: "Active",
    notes: "Premium plan. Expanding to second location.",
  },
  {
    id: "10",
    companyName: "Heartland Heating",
    ownerName: "Steve Cooper",
    phone: "(816) 555-1905",
    email: "steve@heartlandheating.com",
    dealValue: 2400,
    stage: "Active",
    notes: "Steady client. Monthly reviews.",
  },
];

// ─── Systems ──────────────────────────────────────────────
export const mockSystems: ConnectedSystem[] = [
  {
    id: "sys-1",
    name: "Supabase",
    description: "Database, auth, and storage backend for all projects",
    url: "https://app.supabase.com",
    health: "Operational",
    lastChecked: "2026-02-18T02:30:00Z",
    icon: "Database",
    error: null,
  },
  {
    id: "sys-2",
    name: "n8n",
    description: "Workflow automation — lead enrichment, notifications, reporting",
    url: "https://n8n.homfieldhub.com",
    health: "Operational",
    lastChecked: "2026-02-18T02:30:00Z",
    icon: "Workflow",
    error: null,
  },
  {
    id: "sys-3",
    name: "VAPI",
    description: "AI voice agents for inbound and outbound calls",
    url: "https://dashboard.vapi.ai",
    health: "Degraded",
    lastChecked: "2026-02-18T02:15:00Z",
    icon: "Mic",
    error: "Outbound agent latency spiked to 3.2s avg (target <1.5s). Investigating.",
  },
  {
    id: "sys-4",
    name: "Stripe",
    description: "Payment processing, subscriptions, and invoicing",
    url: "https://dashboard.stripe.com",
    health: "Operational",
    lastChecked: "2026-02-18T02:30:00Z",
    icon: "CreditCard",
    error: null,
  },
  {
    id: "sys-5",
    name: "Twilio",
    description: "Phone numbers, SMS, and voice infrastructure for cold calling",
    url: "https://console.twilio.com",
    health: "Operational",
    lastChecked: "2026-02-18T02:30:00Z",
    icon: "Phone",
    error: null,
  },
  {
    id: "sys-6",
    name: "Slack",
    description: "Team communications and automated notifications",
    url: "https://app.slack.com",
    health: "Operational",
    lastChecked: "2026-02-18T02:30:00Z",
    icon: "MessageSquare",
    error: null,
  },
  {
    id: "sys-7",
    name: "Notion",
    description: "Task management, documentation, and knowledge base",
    url: "https://notion.so",
    health: "Operational",
    lastChecked: "2026-02-18T02:30:00Z",
    icon: "BookOpen",
    error: null,
  },
  {
    id: "sys-8",
    name: "Vercel",
    description: "Hosting and deployment for Next.js applications",
    url: "https://vercel.com/dashboard",
    health: "Operational",
    lastChecked: "2026-02-18T02:30:00Z",
    icon: "Globe",
    error: null,
  },
  {
    id: "sys-9",
    name: "Meta Ads",
    description: "Facebook and Instagram advertising platform",
    url: "https://business.facebook.com",
    health: "Operational",
    lastChecked: "2026-02-18T01:45:00Z",
    icon: "Megaphone",
    error: null,
  },
  {
    id: "sys-10",
    name: "Google Ads",
    description: "Search and display advertising campaigns",
    url: "https://ads.google.com",
    health: "Unknown",
    lastChecked: "2026-02-17T22:00:00Z",
    icon: "Search",
    error: "Last check was >4 hours ago. May need re-authentication.",
  },
];
